// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaRopa.Data; // ✅ corregido el namespace

#nullable disable

namespace TiendaRopa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419094544_AuditoriaCliente")]
    partial class AuditoriaCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Aquí EF Core describe las entidades de tu modelo actual
            // Por ejemplo, Cliente, ProductoRopa, Venta, VentaDetalle, etc.
            // Este archivo se genera automáticamente y no necesita Up/Down.
#pragma warning restore 612, 618
        }
    }
}
