// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaRopa.Data;

#nullable disable

namespace TiendaRopa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413173627_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Cliente
            modelBuilder.Entity("TiendaRopa.Entidades.Cliente", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Extension")
                    .HasMaxLength(10)
                    .HasColumnType("nvarchar(10)");

                b.HasKey("Id");

                b.ToTable("Cliente");
            });

            // Categoria
            modelBuilder.Entity("TiendaRopa.Entidades.Categoria", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.ToTable("Categoria");
            });

            // ProductoRopa
            modelBuilder.Entity("TiendaRopa.Entidades.ProductoRopa", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Talla")
                    .HasMaxLength(10)
                    .HasColumnType("nvarchar(10)");

                b.Property<decimal>("Precio")
                    .HasColumnType("decimal(10,2)");

                b.Property<int>("Stock")
                    .HasColumnType("int");

                b.Property<int>("CategoriaId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("CategoriaId");

                b.ToTable("ProductoRopa");
            });

            // Venta
            modelBuilder.Entity("TiendaRopa.Entidades.Venta", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<DateTime>("Fecha")
                    .HasColumnType("datetime2");

                b.Property<decimal>("Total")
                    .HasColumnType("decimal(10,2)");

                b.Property<int>("ClienteId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("ClienteId");

                b.ToTable("Venta");
            });

            // VentaDetalle
            modelBuilder.Entity("TiendaRopa.Entidades.VentaDetalle", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("VentaId")
                    .HasColumnType("int");

                b.Property<int>("ProductoId")
                    .HasColumnType("int");

                b.Property<int>("Cantidad")
                    .HasColumnType("int");

                b.Property<decimal>("PrecioUnitario")
                    .HasColumnType("decimal(10,2)");

                b.HasKey("Id");

                b.HasIndex("VentaId");
                b.HasIndex("ProductoId");

                b.ToTable("VentaDetalle");
            });

            // Relaciones
            modelBuilder.Entity("TiendaRopa.Entidades.Venta", b =>
            {
                b.HasOne("TiendaRopa.Entidades.Cliente", "Cliente")
                    .WithMany("Ventas")
                    .HasForeignKey("ClienteId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Cliente");
            });

            modelBuilder.Entity("TiendaRopa.Entidades.ProductoRopa", b =>
            {
                b.HasOne("TiendaRopa.Entidades.Categoria", "Categoria")
                    .WithMany("Productos")
                    .HasForeignKey("CategoriaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Categoria");
            });

            modelBuilder.Entity("TiendaRopa.Entidades.VentaDetalle", b =>
            {
                b.HasOne("TiendaRopa.Entidades.Venta", "Venta")
                    .WithMany("Detalles")
                    .HasForeignKey("VentaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("TiendaRopa.Entidades.ProductoRopa", "Producto")
                    .WithMany("Detalles")
                    .HasForeignKey("ProductoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Venta");
                b.Navigation("Producto");
            });

            modelBuilder.Entity("TiendaRopa.Entidades.Cliente", b =>
            {
                b.Navigation("Ventas");
            });

            modelBuilder.Entity("TiendaRopa.Entidades.Categoria", b =>
            {
                b.Navigation("Productos");
            });

            modelBuilder.Entity("TiendaRopa.Entidades.Venta", b =>
            {
                b.Navigation("Detalles");
            });

            modelBuilder.Entity("TiendaRopa.Entidades.ProductoRopa", b =>
            {
                b.Navigation("Detalles");
            });
#pragma warning restore 612, 618
        }
    }
}
